// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvwiguxwhvqgximowrxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2d2lndXh3aHZxZ3hpbW93cnhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjM5MjYsImV4cCI6MjA2MDc5OTkyNn0.9WOEtHntfqCSoTIXpBGg6o5B4SxhYv8RAtkyxEO5mdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);