// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkpvmfsviyzjynbiwqzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrcHZtZnN2aXl6anluYml3cXp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNTEzNjMsImV4cCI6MjA1NjcyNzM2M30.3cjKfbvE1c6nxRFpalPO_2vwSwV0z9V-5OwsjnqCZ5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);